spring.application.name=bts-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/bts-db
spring.datasource.username=postgres
spring.datasource.password=bazepodataka
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
bts.gameSecret=01040311